"""HTML compliance report generation."""

from __future__ import annotations

from datetime import datetime, timezone


def generate_html_report(data: dict) -> str:
    """Generate an HTML compliance report from eval results."""
    summary = data.get("summary", {})
    results = data.get("results", [])
    timestamp = data.get("timestamp", "")

    passed = summary.get("passed", 0)
    total = summary.get("total", 0)
    score = summary.get("score", 0)
    total_cost = summary.get("total_cost", 0)

    # Format the timestamp for display
    if timestamp:
        try:
            dt = datetime.strptime(timestamp, "%Y%m%d_%H%M%S").replace(
                tzinfo=timezone.utc
            )
            date_str = dt.strftime("%Y-%m-%d %H:%M:%S UTC")
        except ValueError:
            date_str = timestamp
    else:
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    # Build table rows
    rows = ""
    for r in results:
        name = _escape(r.get("name", "unknown"))
        status = r.get("status", "unknown")
        error = _escape(r.get("error", ""))
        cost = r.get("cost", 0)
        latency = r.get("latency", 0)

        if status == "passed":
            badge = '<span class="badge pass">PASS</span>'
        elif status == "failed":
            badge = '<span class="badge fail">FAIL</span>'
        else:
            badge = '<span class="badge">' + _escape(status.upper()) + "</span>"

        error_cell = f'<span class="error">{error}</span>' if error else ""

        rows += f"""        <tr>
          <td>{name}</td>
          <td>{badge}</td>
          <td>${cost:.4f}</td>
          <td>{latency:.2f}s</td>
          <td>{error_cell}</td>
        </tr>
"""

    score_class = "pass" if score >= 0.85 else "fail"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>proofagent Evaluation Report</title>
  <style>
    * {{ margin: 0; padding: 0; box-sizing: border-box; }}
    body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; color: #1a1a1a; background: #fafafa; padding: 2rem; }}
    .container {{ max-width: 900px; margin: 0 auto; }}
    h1 {{ font-size: 1.5rem; margin-bottom: 0.25rem; }}
    .meta {{ color: #666; font-size: 0.875rem; margin-bottom: 1.5rem; }}
    .summary {{ display: flex; gap: 2rem; margin-bottom: 2rem; padding: 1rem; background: #fff; border: 1px solid #e0e0e0; border-radius: 6px; }}
    .summary .stat {{ text-align: center; }}
    .summary .stat .value {{ font-size: 1.5rem; font-weight: 700; }}
    .summary .stat .label {{ font-size: 0.75rem; color: #666; text-transform: uppercase; letter-spacing: 0.05em; }}
    .pass {{ color: #16a34a; }}
    .fail {{ color: #dc2626; }}
    table {{ width: 100%; border-collapse: collapse; background: #fff; border: 1px solid #e0e0e0; border-radius: 6px; overflow: hidden; }}
    th {{ text-align: left; padding: 0.75rem 1rem; background: #f5f5f5; font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.05em; color: #666; border-bottom: 1px solid #e0e0e0; }}
    td {{ padding: 0.75rem 1rem; border-bottom: 1px solid #f0f0f0; font-size: 0.875rem; }}
    .badge {{ font-weight: 600; font-size: 0.75rem; padding: 0.15rem 0.5rem; border-radius: 3px; }}
    .badge.pass {{ background: #dcfce7; color: #16a34a; }}
    .badge.fail {{ background: #fee2e2; color: #dc2626; }}
    .error {{ color: #666; font-size: 0.8rem; }}
    .footer {{ margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #e0e0e0; font-size: 0.75rem; color: #999; }}
  </style>
</head>
<body>
  <div class="container">
    <h1>proofagent Evaluation Report</h1>
    <div class="meta">{date_str}</div>

    <div class="summary">
      <div class="stat">
        <div class="value {score_class}">{score:.0%}</div>
        <div class="label">Pass Rate</div>
      </div>
      <div class="stat">
        <div class="value">{passed}/{total}</div>
        <div class="label">Tests Passed</div>
      </div>
      <div class="stat">
        <div class="value">${total_cost:.4f}</div>
        <div class="label">Total Cost</div>
      </div>
    </div>

    <table>
      <thead>
        <tr>
          <th>Test</th>
          <th>Status</th>
          <th>Cost</th>
          <th>Latency</th>
          <th>Details</th>
        </tr>
      </thead>
      <tbody>
{rows}      </tbody>
    </table>

    <div class="footer">
      This report is generated by proofagent for informational purposes only and does not constitute a safety certification.
    </div>
  </div>
</body>
</html>"""


def _escape(text: str) -> str:
    """Escape HTML special characters."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
